# This file is auto-generated by nixos-generate-config
# You'll create this during NixOS installation
# It contains hardware-specific configuration

# PLACEHOLDER - Replace this with your actual hardware-configuration.nix
# after running: sudo nixos-generate-config

{ config, lib, pkgs, modulesPath, ... }:

{
  # This is a TEMPLATE - your actual hardware config will be different
  # Run this command on a NixOS system to generate it:
  #   sudo nixos-generate-config --show-hardware-config
  
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  # Example boot configuration - yours will differ
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ]; # or "kvm-amd" for AMD
  
  # Example filesystem configuration - yours will differ
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX";
    fsType = "ext4";
  };
  
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/XXXX-XXXX";
    fsType = "vfat";
  };

  # Swap configuration (if you have swap)
  # swapDevices = [ ];
  
  # Network interfaces
  # networking.useDHCP = lib.mkDefault true;
  
  # CPU microcode
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # OR for AMD:
  # hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
